version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 127.0.0.1:1337:1337
    volumes:
      - uploads:/app/backend/public/uploads
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_USER: strapi
    volumes:
      - db:/var/lib/postgresql/data
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - 127.0.0.1:3002:3000
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis:/var/lib/redis
  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    restart: unless-stopped

volumes:
  uploads:
  db:
  redis:
