version: "3.7"

services:
  backend:
    image: node:14
    depends_on:
      - db
    ports:
      - 127.0.0.1:1337:1337
    volumes:
      - .:/app
      - /app/backend/.cache
      - /app/backend/build
      - backend_nm:/app/backend/node_modules
    working_dir: /app/backend
    command: /app/shared/start-docker-dev.sh backend
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_USER: strapi
  frontend:
    image: node:14
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - .:/app
      - /app/frontend/.next
      - frontend_nm:/app/frontend/node_modules
    working_dir: /app/frontend
    command: /app/shared/start-docker-dev.sh frontend
  redis:
    image: redis:latest
    restart: unless-stopped
  worker:
    image: node:14
    restart: unless-stopped
    volumes:
      - .:/app
      - worker_nm:/app/worker/node_modules
    working_dir: /app/worker
    command: /app/shared/start-docker-dev.sh worker

volumes:
  backend_nm:
  frontend_nm:
  worker_nm:
