version: "3.7"

services:
  backend:
    image: node:14
    command: /app/docker/start backend
    env_file: .env
    ports:
      - "${BACKEND_BIND:-127.0.0.1}:${BACKEND_PORT:-1337}:1337"
    restart: unless-stopped
    volumes:
      - .:/app:delegated
      - ~/.npm/docker-cache:/home/node/.npm:cached
      - /app/backend/.cache
      - /app/backend/build
      - backend_nm:/app/backend/node_modules
      - backend_snm:/app/shared/node_modules
    working_dir: /app/backend

  frontend:
    image: node:14
    command: /app/docker/start frontend
    environment:
      NEXT_PUBLIC_BACKEND_URL: ${BACKEND_URL:-http://localhost:1337}
      NEXT_PUBLIC_HCAPTCHA_SITE_KEY: ${HCAPTCHA_SITE_KEY:-}
      NEXT_PUBLIC_PLAUSIBLE_DOMAIN_KEY: ${PLAUSIBLE_DOMAIN_KEY:-localhost}
      NEXT_PUBLIC_PLAUSIBLE_URL: ${PLAUSIBLE_URL:-https://plausible.pujas.live}
      NEXT_PUBLIC_S3_BUCKET: ${S3_BUCKET:-}
      NEXT_PUBLIC_S3_ENDPOINT: ${S3_ENDPOINT:-}
      NEXT_PUBLIC_SITE_NAME: ${SITE_NAME:-Pujas.live}
    ports:
      - "${FRONTEND_BIND:-127.0.0.1}:${FRONTEND_PORT:-3000}:3000"
    restart: unless-stopped
    volumes:
      - .:/app:delegated
      - ~/.npm/docker-cache:/home/node/.npm:cached
      - /app/frontend/.next
      - frontend_nm:/app/frontend/node_modules
      - frontend_snm:/app/shared/node_modules
    working_dir: /app/frontend

  mail:
    image: mahadana/mail:latest
    env_file: .env
    restart: unless-stopped

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_USER: strapi
    restart: unless-stopped

  redis:
    image: redis:latest
    restart: unless-stopped

  worker:
    image: node:14
    command: /app/docker/start worker
    env_file: .env
    restart: unless-stopped
    volumes:
      - .:/app:delegated
      - ~/.npm/docker-cache:/home/node/.npm:cached
      - worker_nm:/app/worker/node_modules
      - worker_snm:/app/shared/node_modules
    working_dir: /app/worker

volumes:
  backend_nm:
  backend_snm:
  frontend_nm:
  frontend_snm:
  worker_nm:
  worker_snm:
